version: "3.7"
services:

#Laravel App
  app:
    build:
      args:
        user: martin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-2021-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mynetwork

 #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: laravel-2021-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - mysql
    networks:
      - mynetwork

  #Mysl Service
  mysql:
    image: mariadb:10.5
    container_name: laravel-2021-mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./dumps/:/home/dumps
      #- ./dumps/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
    ports:
      - 3307:3306
    networks:
      - mynetwork

  #MailHog
  mailhog:
    image: mailhog/mailhog:latest
    container_name: laravel-2021-mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
